import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "@/utils/Provider";
import Navbar from "@/components/layout/Navbar";
import SplashScreen from "@/components/core/SplashScreen";

const inter = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} antialiased`}>
        <Web3Provider>
          <SplashScreen />

          <header>
            <Navbar />
          </header>
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
